# Generated by Django 2.1.7 on 2019-03-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='reply_to',
            field=models.CharField(blank=True, help_text='Email that people can choose to reply to for any information emails.', max_length=250, verbose_name='reply_to'),
        ),
    ]
